spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database name
    driver-class-name: org.postgresql.Driver
    username: your postgres username
    password: your password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret-key: your secret key